version: 2

sources:
  - name: source_bronze
    database: pysparkdbt
    schema: bronze  
    tables:
      - name: trips


  - name: source_silver
    database: pysparkdbt
    schema: silver 
    tables:
      - name: customers
      - name: locations
      - name: drivers
      - name: payments
      - name: vehicles
